apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: edct3uos5-nodejs
  janus-idp.io/tekton: edct3uos5-nodejs
  backstage.io/kubernetes-id: edct3uos5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: edct3uos5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
